- tools/install.sh
upd install.sh with:
* some installation parameters
* a help menu
* if rtklib is already installed do nothing
* clean and make new functions
> modify install.sh with some installation parameters

- README.md
change url so that it is not relative to the github url
> Update README for ED url

- web_app/server.py
- web_app/templates/diagnostic.html
- web_app/templates/settings.html
> Adding a diagnostic report

- web_app/static/settings.js
- web_app/templates/settings.html
On a reboot, the web service display a spinner, and auto refresh the web page after 60 seconds
> Spinner on reboot

- archive_and_clean.sh
- tools/install.sh
> Check space

- web_app/RTKLIB.py
- web_app/RtkController.py
- web_app/server.py
checking receiver path and type when launching rtkrcv. Rtkrcv is in use for realtime base location.
fix #148
> Rtkrcv input type

- web_app/server.py
- web_app/static/settings.js
- web_app/templates/settings.html
> Adding cpu temperature on setting webpage

- tools/install.sh
This allow to give a second chance to detect the GNSS brand thank to the usb vendorID.
This is usefull on Docker environment were udevadm database isn't complete and thus prevent the current method to work.
> tools: add a second way to try to detect Ublox GNSS

- web_app/server.py
- web_app/static/settings.js
With this, the webpage will detect when the rtkbase update is terminated, and display the information to the user.
It should fix #46 
I didn't find a solution to clear the browser cache after the update.
> Auto refresh after update

- tools/install.sh
With `ExecStartPre=....` gpsd starts only if the `str2str_tcp.service` is running. If this service stop, gpsd doesn't stop and just wait for incoming data.
> Should fix gpsd starting problems #94

- web_app/RTKBaseConfigManager.py
- web_app/server.py
- web_app/static/logs.js
- web_app/static/settings.js
- web_app/templates/settings.html
Adding feature to import, export and reset RTKBase settings
> Import export reset settings

- run_cast.sh
- settings.conf.default
- tools/install.sh
- web_app/RTKBaseConfigManager.py
- web_app/templates/settings.html
- Get F9P firmware release number during the configuration
- Display Model / Firmware on the settings page
- Send the firmware in the rtcm stream
> Get firmware

- web_app/RTKLIB.py
- web_app/static/graph.js
Closes #72 
Maybe we should remove the hardcoded `NUMBER_OF_SATELLITES = 37` and implement a horizontal scrollable axis instead? This would allow for better readability on small screens (e.g. phones) as well.
> Fix satellite bar alignment and optimize graph update

- tools/install.sh
Corrected error in IP address for gpsd.conf
> Corrected error in gpsd.conf IP address

- tools/install.sh
Switch 127.0.0.1 to localhost to avoid issues with changed loopback addresses or IPv6-only stacks.
> Switch 127.0.0.1 to localhost

- web_app/server.py
Switch 127.0.0.1 to localhost and 0.0.0.0 to INADDR_ANY to avoid issues with changed loopback addresses or IPv6-only stacks.
> Switch 127.0.0.1 to localhost and 0.0.0.0 to INADDR_ANY

- CHANGELOG.md
- archive_and_clean.sh
- rtkbase_update.sh
- run_cast.sh
- tools/convbin.sh
- tools/install.sh
- web_app/server.py
- Add more info in rinex file (approximate position, rtkbase release
- remove 2 frequencies limit for full and full 30s presets
- get receiver option from settings.conf (-TADJ=1 not hardcoded anymore)
> convbin script update

- CHANGELOG.md
- web_app/gnss_rproxy_server.py
- web_app/requirements.txt
- web_app/server.py
eventlet is causing me some problems with gunicorn. This MR switch from eventlet to gevent, and use gunicorn.
> Use gunicorn and gevent

- CHANGELOG.md
- web_app/network_infos.py
- web_app/server.py
- web_app/static/settings.js
- web_app/templates/settings.html
Show network interface and their ip addresses on the GUI :
> Show network info

- CHANGELOG.md
- README.md
- tools/find_rtkbase/scan_network.py
- tools/install.sh
Merge cleaning and readme update
> Detect rtkbase
